/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseholdsSecretOnboardingRouteImport } from './routes/households.$secret.onboarding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsSecretOnboardingRoute =
  HouseholdsSecretOnboardingRouteImport.update({
    id: '/households/$secret/onboarding',
    path: '/households/$secret/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/households/$secret/onboarding': typeof HouseholdsSecretOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/households/$secret/onboarding': typeof HouseholdsSecretOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/households/$secret/onboarding': typeof HouseholdsSecretOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/households/$secret/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/households/$secret/onboarding'
  id: '__root__' | '/' | '/households/$secret/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HouseholdsSecretOnboardingRoute: typeof HouseholdsSecretOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/$secret/onboarding': {
      id: '/households/$secret/onboarding'
      path: '/households/$secret/onboarding'
      fullPath: '/households/$secret/onboarding'
      preLoaderRoute: typeof HouseholdsSecretOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HouseholdsSecretOnboardingRoute: HouseholdsSecretOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
